export const DATA_SOURCE = 'DATA_SOURCE';

export const MOMENT_PACKAGE = 'MOMENT_PACKAGE';

export const AIRPORTS_REPOSITORY = 'AIRPORTS_REPOSITORY';
export const CITIES_REPOSITORY = 'CITIES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const TRIPS_REPOSITORY = 'TRIPS_REPOSITORY';
